name: Migration Check

on:
  push:
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/migration-check.yml'
  pull_request:
    paths:
      - 'supabase/migrations/**'

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Supabase CLI
      run: |
        npm install -g supabase
        
    - name: Check Migration Files
      run: |
        echo "🔍 마이그레이션 파일 검사 중..."
        ls -la supabase/migrations/
        
    - name: Validate SQL Syntax
      run: |
        for file in supabase/migrations/*.sql; do
          echo "✓ Checking $file"
          # SQL 문법 검사 (기본)
          if ! grep -q "CREATE\|ALTER\|DROP\|INSERT" "$file"; then
            echo "⚠️ Warning: $file may not contain valid SQL"
          fi
        done
        
    - name: Auto Migration (if secrets available)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        if [ ! -z "$DATABASE_URL" ]; then
          npm run supabase:auto-migrate
        else
          echo "⚠️ DATABASE_URL not set, skipping auto migration"
        fi